springdoc.swagger-ui.defaultModelsExpandDepth=-1
management.endpoints.web.exposure.include=*

spring.config.import=optional:configserver:
spring.cloud.config.token=myroot
spring.cloud.config.uri=http://localhost:5050
spring.cloud.config.name=tiny-db,tiny-application
spring.cloud.config.profile=default