spring:
  profiles:
    active: common
    
    
---


  
spring:
  config:
    activate:
      on-profile: common

  application:
    name: tiny-discovery-server
    
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
    
server:
  port: 6060